# Generated by Django 5.0.3 on 2024-03-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainsncf',
            fields=[
                ('TrainID', models.AutoField(primary_key=True, serialize=False)),
                ('City', models.CharField(max_length=100)),
                ('Departure_Time', models.TimeField(verbose_name=10)),
                ('Arrival_Time', models.TimeField(max_length=10)),
            ],
        ),
    ]
